auth0:
  audience:  ${AUTH0_AUDIENCE}

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: expense-manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_JWT_ISSUER_URL}

server:
  servlet:
    context-path: /api

mongock:
  migration-scan-package: com.main.expensemanagerapi.migration
