spring:
  data:
    mongodb:
      uri: mongodb+srv://expense-manager-dev:6Gru3iDfZW2EhRuK@cluster0.rbcxf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: myFirstDatabase

mongock:
  migration-scan-package: com.main.expensemanagerapi.migration